// Хэсэг/дэд хэсэг тус бүрийн үндсэн тоног төхөөрөмжийн каталог (Excel бүртгэлээс)
export const MAIN_EQUIPMENTS_BY_SUB_SECTION: Record<string, { code: string; label: string }[]> = {
  "DTO|KKD1": [
    { code: "CON1A", label: "Conveyor #1A" },
    { code: "CON2A", label: "Conveyor #2A" },
    { code: "CON3", label: "Conveyor #3" },
    { code: "CRU1", label: "Crusher #1" },
    { code: "CRU2", label: "Crusher #2" },
  ],
  "DTO|KMD": [
    { code: "CON12", label: "Conveyor #12" },
    { code: "CON13", label: "Conveyor #13" },
    { code: "CON14", label: "Conveyor #14" },
    { code: "CON15", label: "Conveyor #15" },
    { code: "CON16", label: "Conveyor #16" },
    { code: "CON16A", label: "Conveyor #16A" },
    { code: "CRU12", label: "Crusher #12" },
    { code: "CRU13", label: "Crusher #13" },
    { code: "CRU14", label: "Crusher #14" },
    { code: "CRU15", label: "Crusher #15" },
    { code: "CRU16", label: "Crusher #16" },
    { code: "CRU16A", label: "Crusher #16A" },
  ],
  "DTO|KSD": [
    { code: "CON4", label: "Conveyor #4" },
    { code: "CON5", label: "Conveyor #5" },
    { code: "CON6", label: "Conveyor #6" },
    { code: "CON7", label: "Conveyor #7" },
    { code: "CON8", label: "Conveyor #8" },
    { code: "CRU4", label: "Crusher #4" },
    { code: "CRU5", label: "Crusher #5" },
    { code: "CRU6", label: "Crusher #6" },
    { code: "CRU7", label: "Crusher #7" },
    { code: "CRU8", label: "Crusher #8" },
  ],
  "DTO|SKDR": [
    { code: "CON9", label: "Conveyor #9" },
    { code: "CON11", label: "Conveyor #11" },
    { code: "CON17", label: "Conveyor #17" },
    { code: "PUM501502", label: "Pump #501/502" },
    { code: "PUM505", label: "Pump #505" },
    { code: "PUM507508", label: "Pump #507/508" },
  ],
  "FSO|CC": [
    { code: "CON54", label: "Conveyor #54" },
    { code: "CON55", label: "Conveyor #55" },
    { code: "CON56", label: "Conveyor #56" },
    { code: "CCS6869", label: "Copper concentrat sump #68,69" },
    { code: "CCT64", label: "Copper concentrat tank #64" },
    { code: "CCT65", label: "Copper concentrat tank #65" },
    { code: "PF1", label: "Press filter #1" },
    { code: "PF2", label: "Press filter #2" },
    { code: "PF3", label: "Press filter #3" },
    { code: "TP3", label: "Thickener pump #3" },
    { code: "TP4", label: "Thickener pump #4" },
    { code: "TP5", label: "Thickener pump #5" },
  ],
  "FSO|MC": [
    { code: "EO2", label: "Electric oven #2" },
    { code: "EO3", label: "Electric oven #3" },
    { code: "MCS7071", label: "Molibden concentrat sump #70,71" },
    { code: "MCS7273", label: "Molibden concentrat sump #72,73" },
    { code: "MCT66", label: "Molibden concentrat tank #66" },
    { code: "MCT67", label: "Molibden concentrat tank #67" },
    { code: "PF4", label: "Press filter #4" },
    { code: "PF5", label: "Press filter #5" },
    { code: "PF6", label: "Press filter #6" },
    { code: "PF7", label: "Press filter #7" },
    { code: "VF", label: "Vacuum filter" },
  ],
  "FSO|MN": [
    { code: "CON62", label: "Conveyor #62" },
    { code: "WT8484A", label: "Water tank #84,84A" },
    { code: "WT94", label: "Water tank #94" },
    { code: "WT125", label: "Water tank #125" },
  ],
  "IFO|ACS": [
    { code: "AC3", label: "Air compressor #3" },
    { code: "AC4", label: "Air compressor #4" },
    { code: "AC173", label: "Air compressor #173" },
    { code: "AC174", label: "Air compressor #174" },
    { code: "AC175", label: "Air compressor #175" },
    { code: "AC176", label: "Air compressor #176" },
    { code: "NAC1", label: "New air compressor #1" },
  ],
  "IFO|ML": [
    { code: "BM1", label: "Ball Mill #1" },
    { code: "BM1A", label: "Ball Mill #1A" },
    { code: "BM2", label: "Ball Mill #2" },
    { code: "BM3", label: "Ball Mill #3" },
    { code: "BM4", label: "Ball Mill #4" },
    { code: "BM5", label: "Ball Mill #5" },
    { code: "BM6", label: "Ball Mill #6" },
    { code: "BM7", label: "Ball Mill #7" },
    { code: "BM8", label: "Ball Mill #8" },
    { code: "CON19", label: "Conveyor #19" },
    { code: "CON19A", label: "Conveyor #19A" },
    { code: "CON20", label: "Conveyor #20" },
    { code: "CON21", label: "Conveyor #21" },
    { code: "CON22", label: "Conveyor #22" },
    { code: "CON23", label: "Conveyor #23" },
    { code: "CON24", label: "Conveyor #24" },
    { code: "CON25", label: "Conveyor #25" },
    { code: "CON26", label: "Conveyor #26" },
    { code: "MIL", label: "Mills" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|MS": [
    { code: "FC", label: "Flotation cells" },
    { code: "FC84", label: "Flotation cells #84" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|NMS": [
    { code: "FC", label: "Flotation cells" },
    { code: "RD", label: "Reagent doser" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|OMS": [
    { code: "FC", label: "Flotation cells" },
    { code: "RD", label: "Reagent doser" },
  ],
  "IFO|S1": [
    { code: "FC", label: "Flotation cells" },
    { code: "MIL9", label: "Mill #9" },
    { code: "MIL10", label: "Mill #10" },
    { code: "MIL11", label: "Mill #11" },
    { code: "MIL12", label: "Mill #12" },
    { code: "RD", label: "Reagent doser" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|S2": [
    { code: "FC", label: "Flotation cells" },
    { code: "MIL13", label: "Mill #13" },
    { code: "MIL14", label: "Mill #14" },
    { code: "RD", label: "Reagent doser" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|S3": [
    { code: "FC", label: "Flotation cells" },
    { code: "MIL15", label: "Mill #15" },
    { code: "MIL16", label: "Mill #16" },
    { code: "RD", label: "Reagent doser" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|S4": [
    { code: "FC", label: "Flotation cells" },
    { code: "MIL17", label: "Mill #17" },
    { code: "MIL18", label: "Mill #18" },
    { code: "RD", label: "Reagent doser" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|S5": [
    { code: "FC", label: "Flotation cells" },
    { code: "MIL23", label: "Mill #23" },
    { code: "MIL24", label: "Mill #24" },
    { code: "RD", label: "Reagent doser" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|S6": [
    { code: "FC", label: "Flotation cells" },
    { code: "MIL26", label: "Mill #26" },
    { code: "RD", label: "Reagent doser" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "IFO|SS": [
    { code: "FC", label: "Flotation cells" },
    { code: "FC49", label: "Flotation cells #49" },
    { code: "SS", label: "Slurry sumps" },
  ],
  "KSI|KKD2": [
    { code: "CON71", label: "Conveyor #71" },
    { code: "JC1", label: "Jaw Crusher #1" },
    { code: "JC2", label: "Jaw Crusher #2" },
    { code: "JC3", label: "Jaw Crusher #3" },
  ],
  "KSI|PS": [
    { code: "CWS", label: "Circulating water S1,S2,S3" },
    { code: "CWSB", label: "Circulating water S4" },
    { code: "PUM578", label: "Pump #578" },
    { code: "PUM579", label: "Pump #579" },
    { code: "EQ", label: "Насос станц" },
  ],
  "KSI|S1": [
    { code: "BD", label: "Ball doser" },
    { code: "BM3", label: "Ball Mill #3" },
    { code: "CON72", label: "Conveyor #72" },
    { code: "CON73", label: "Conveyor #73" },
    { code: "HYD15", label: "HydroCyclone #15" },
    { code: "HYD16", label: "HydroCyclone #16" },
    { code: "HYD18", label: "HydroCyclone #18" },
    { code: "HYD19", label: "HydroCyclone #19" },
    { code: "LD", label: "Lime doser" },
    { code: "PUM15", label: "Pump #15" },
    { code: "PUM18", label: "Pump #18" },
    { code: "PUM19", label: "Pump #19" },
    { code: "RD", label: "Reagent doser" },
    { code: "SM1", label: "SAG Mill #1" },
    { code: "SIL1", label: "Silo #1" },
    { code: "SIL2", label: "Silo #2" },
    { code: "WAT", label: "Water" },
  ],
  "KSI|S2": [
    { code: "BD", label: "Ball doser" },
    { code: "BM4", label: "Ball Mill #4" },
    { code: "CON74", label: "Conveyor #74" },
    { code: "CON75", label: "Conveyor #75" },
    { code: "HYD20", label: "HydroCyclone #20" },
    { code: "HYD21", label: "HydroCyclone #21" },
    { code: "HYD22", label: "HydroCyclone #22" },
    { code: "HYD23", label: "HydroCyclone #23" },
    { code: "LD", label: "Lime doser" },
    { code: "PUM20", label: "Pump #20" },
    { code: "PUM23", label: "Pump #23" },
    { code: "RD", label: "Reagent doser" },
    { code: "SM2", label: "SAG Mill #2" },
    { code: "SIL3", label: "Silo #3" },
    { code: "SIL4", label: "Silo #4" },
    { code: "WAT", label: "Water" },
  ],
  "KSI|S3": [
    { code: "BM6", label: "Ball Mill #6" },
    { code: "CON80", label: "Conveyor #80" },
    { code: "CON81", label: "Conveyor #81" },
    { code: "CON82A", label: "Conveyor #82a" },
    { code: "CON82B", label: "Conveyor #82b" },
    { code: "CON83", label: "Conveyor #83" },
    { code: "GAS", label: "Gas" },
    { code: "HYD24", label: "HydroCyclone #24" },
    { code: "HYD25", label: "HydroCyclone #25" },
    { code: "KC1", label: "KMD Crusher #1" },
    { code: "KC2", label: "KMD Crusher #2" },
    { code: "LD", label: "Lime doser" },
    { code: "LS", label: "Lubrication station" },
    { code: "PUM24", label: "Pump #24" },
    { code: "PUM25", label: "Pump #25" },
    { code: "RD", label: "Reagent doser" },
    { code: "SM5", label: "SAG Mill #5" },
    { code: "SIL5", label: "Silo #5" },
    { code: "SIL6", label: "Silo #6" },
    { code: "VS1", label: "Vibrating screen #1" },
    { code: "VS2", label: "Vibrating screen #2" },
    { code: "WAT", label: "Water" },
  ],
  "KSI|S4": [
    { code: "BD", label: "Ball doser" },
    { code: "BM8", label: "Ball Mill #8" },
    { code: "BM9", label: "Ball Mill #9" },
    { code: "CON84", label: "Conveyor #84" },
    { code: "CON85", label: "Conveyor #85" },
    { code: "CON87", label: "Conveyor #87" },
    { code: "CON88", label: "Conveyor #88" },
    { code: "CON89", label: "Conveyor #89" },
    { code: "CW", label: "Cooling water" },
    { code: "GAS", label: "Gas" },
    { code: "HYD30", label: "HydroCyclone #30" },
    { code: "HYD31", label: "HydroCyclone #31" },
    { code: "KC3", label: "KMD Crusher #3" },
    { code: "KC4", label: "KMD Crusher #4" },
    { code: "LD", label: "Lime doser" },
    { code: "LS", label: "Lubrication station" },
    { code: "PUM30", label: "Pump #30" },
    { code: "PUM31", label: "Pump #31" },
    { code: "RD", label: "Reagent doser" },
    { code: "SM7", label: "SAG Mill #7" },
    { code: "SIL7", label: "Silo #7" },
    { code: "SIL8", label: "Silo #8" },
    { code: "VS1", label: "Vibrating screen #1" },
    { code: "VS2", label: "Vibrating screen #2" },
    { code: "WAT", label: "Water" },
  ],
  "PNS|0": [
    { code: "RWP1", label: "Recirculating water pipeline #1" },
    { code: "RWP2", label: "Recirculating water pipeline #2" },
    { code: "SP1", label: "Slurry pipeline #1" },
    { code: "SP2", label: "Slurry pipeline #2" },
    { code: "SP3", label: "Slurry pipeline #3" },
    { code: "SPP1", label: "Slurry pressure pipeline #1" },
    { code: "SPP2", label: "Slurry pressure pipeline #2" },
  ],
  "RO|0": [
    { code: "CON45", label: "Conveyor #45" },
    { code: "CON46", label: "Conveyor #46" },
    { code: "CON47", label: "Conveyor #47" },
    { code: "MIL1", label: "Mill #1" },
    { code: "MIL2", label: "Mill #2" },
    { code: "MIL3", label: "Mill #3" },
    { code: "TAN5", label: "Tank #5" },
    { code: "TAN6", label: "Tank #6" },
    { code: "TAN7", label: "Tank #7" },
    { code: "TAN8", label: "Tank #8" },
    { code: "TAN9", label: "Tank #9" },
    { code: "TAN9A", label: "Tank #9a" },
    { code: "TAN10", label: "Tank #10" },
    { code: "TAN11", label: "Tank #11" },
    { code: "TAN12", label: "Tank #12" },
  ],
};

export function mainEquipmentOptions(section: string, subSection: string) {
  return MAIN_EQUIPMENTS_BY_SUB_SECTION[`${section}|${subSection}`] ?? [];
}

export function mainEquipmentLabel(section: string, subSection: string, code: string) {
  const found = mainEquipmentOptions(section, subSection).find((m) => m.code === code);
  return found ? found.label : code;
}
